### ISSUE TITLE
good tool

### ISSUE THREAD

**Issue by koala-222** [HappyCtest/NJU_NetworkLogin#2]
Convient and Fast!
a little advice: with vpn on, it's not always stable

**Comment by btyu** [comment]
I think it is because your VPN cannot reach the network login website. Try one of the two solutions:
- Set your VPN (recommended): make it connect 219.219.114.172 in a direct way.
- Try changing "219.219.114.172" in main.py into "p.nju.edu.cn/". However, it is not recommended because using the IP address instead of the domain name should be robust in a DNS error.

**Comment by koala-222** [comment]
good advice👍
